blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/vikrantblu/diff_and_compare_tool/discussions
    about: Ask questions, share ideas, and connect with the community.
  - name: Security Vulnerability Reporting
    url: https://github.com/vikrantblu/diff_and_compare_tool/security/advisories/new
    about: Privately report security vulnerabilities.
